const FormData = [
    {
        id: 1,
        type: "text",
        label: "Username",
        name: "username",
        placeholder: "Enter your username",
        maxLength: 50,
        required: true,
    },
    {
        id: 2,
        type: "email",
        label: "Email",
        name: "email",
        placeholder: "Enter your email",
        required: true,
    },
    {
        id: 3,
        type: "password",
        label: "Password",
        name: "password",
        placeholder: "Enter your password",
        minLength: 8,
        required: true,
    },
    {
        id: 4,
        type: "checkbox",
        label: "Agree to Terms",
        name: "agreeTerms",
        value: "agree",
        checked: false,
    },
    {
        id: 5,
        type: "select",
        label: "Country",
        name: "country",
        required: true,
        options: [
            { value: "us", text: "United States" },
            { value: "ca", text: "Canada" },
            { value: "in", text: "India" },
        ],
    },
    {
        id: 6,
        type: "textarea",
        label: "Comments",
        name: "comments",
        placeholder: "Enter your comments here",
        rows: 4,
        cols: 50,
    },
    {
        id: 7,
        type: "submit",
        label: "",
        value: "Submit",
    },
    {
        id: 9,
        type: "radio",
        label: "hii",
        value: "Submit",
    },
    {
        id: 8,
        type: "reset",
        label: "",
        value: "reset",
    },
    {
        id: 10,
        type: "text",
        label: "enter your hobby",
        value: "hobby",
        placeholder: "Enter your hobby",
    },
    {
        id: 11,
        type: "multi-checkbox",
        label: "Select Interests",
        name: "interests",
        options: [
            { value: "sports", text: "Sports" },
            { value: "music", text: "Music" },
            { value: "reading", text: "Reading" },
            { value: "coding", text: "Coding" },
        ],
    },
];
export default FormData;